-- Create Trips table
CREATE TABLE Trips (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(255) NOT NULL,
	TripType VARCHAR(50) NOT NULL DEFAULT 'General',
	StartTime DATETIME2 NOT NULL,
	EndTime DATETIME2 NOT NULL,
	CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE()
);

-- Create ChecklistItems table
CREATE TABLE ChecklistItems (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	TripId INT NOT NULL,
	Name VARCHAR(255) NOT NULL,
	IsPacked BIT NOT NULL DEFAULT 0,
	Category VARCHAR(100) NOT NULL DEFAULT 'General',
	PackedAt DATETIME2 NULL,
	FOREIGN KEY (TripId) REFERENCES Trips(Id) ON DELETE CASCADE
);